const guests = [
  { name: "Kak Katrin & Rangga", table: "1", jumlah: "2" },
  { name: "Kak Ica & Bang Aryi", table: "1", jumlah: "2" },
  { name: "Victor & Teena", table: "1", jumlah: "2" },
  { name: "Yehezkiel & Cherry", table: "1", jumlah: "2" },
  { name: "Dea & Kresna", table: "1", jumlah: "2" },
  { name: "Ko Ronny & Keluarga", table: "2", jumlah: "3" },
  { name: "Grace Noel", table: "2", jumlah: "1" },
  { name: "Revina", table: "2", jumlah: "1" },
  { name: "Iva & Kak Jeje", table: "2", jumlah: "2" },
  { name: "Bang Will", table: "2", jumlah: "1" },
  { name: "Nur Hanifah & M. Mustofa", table: "3", jumlah: "2" },
  { name: "Lucas Surya Wibawa & Istri", table: "3", jumlah: "2" },
  { name: "Prasaja & Istri", table: "3", jumlah: "2" },
  { name: "Tante Christin & Suami", table: "3", jumlah: "2" },
  { name: "Pdt Aritonang & Istri", table: "4", jumlah: "2" },
  { name: "Ko Rudi & Istri", table: "4", jumlah: "2" },
  { name: "Babe & Ci Linda", table: "4", jumlah: "2" },
  { name: "Pdt. Sonang Saragi", table: "4", jumlah: "2" },
  { name: "Bu Anjar & Suami", table: "4", jumlah: "2" },
  { name: "Fajar", table: "5", jumlah: "2" },
  { name: "Syurya Deta & Istri", table: "5", jumlah: "2" },
  { name: "Synthia Veronica & Suami", table: "5", jumlah: "2" },
  { name: "Atiek & Suami", table: "5", jumlah: "2" },
  { name: "Mas Budi (Tante Lisa & Anaknya)", table: "5", jumlah: "2" },
  { name: "Yodha & Pasangan", table: "6", jumlah: "2" },
  { name: "Ahmad Aslih Sanana", table: "6", jumlah: "2" },
  { name: "Ivan Dewa & Pasangan", table: "6", jumlah: "2" },
  { name: "Justin & Vania", table: "6", jumlah: "2" },
  { name: "Melvin", table: "6", jumlah: "1" },
  { name: "Feky Henry", table: "7", jumlah: "1" },
  { name: "Laura", table: "7", jumlah: "1" },
  { name: "Alandika Firmansyah", table: "7", jumlah: "1" },
  { name: "Vinsky", table: "7", jumlah: "2" },
  { name: "Dina Shabrina", table: "7", jumlah: "1" },
  { name: "Bella Komara", table: "7", jumlah: "1" },
  { name: "Maria Evelyn", table: "7", jumlah: "1" },
  { name: "Hayyu Adenia", table: "7", jumlah: "1" },
  { name: "Ghina", table: "8", jumlah: "1" },
  { name: "Resti", table: "8", jumlah: "1" },
  { name: "Hana Ilhami", table: "8", jumlah: "1" },
  { name: "Anisa Fauziah", table: "8", jumlah: "1" },
  { name: "Jonathan Miracle (Jomi)", table: "8", jumlah: "1" },
  { name: "Aisya", table: "8", jumlah: "1" },
  { name: "Dhea", table: "8", jumlah: "1" },
  { name: "Dhifa", table: "8", jumlah: "1" },
  { name: "dr. Medika Bintang", table: "9", jumlah: "1" },
  { name: "dr. Armabar Oky", table: "9", jumlah: "1" },
  { name: "Naufal Hanif & Istri", table: "9", jumlah: "2" },
  { name: "Alya Ermita", table: "9", jumlah: "1" },
  { name: "Mas Dwi & Istri", table: "9", jumlah: "2" },
  { name: "Achmad Nu'man Annafis (VIP)", table: "10", jumlah: "1" },
  { name: "Indah Puspitasari", table: "10", jumlah: "1" },
  { name: "Raissa Fauzia", table: "10", jumlah: "1" },
  { name: "Henny", table: "10", jumlah: "1" },
  { name: "Pak Yosi (Tentative)", table: "10", jumlah: "2" },
  { name: "Bude Iik & Suami", table: "11", jumlah: "2" },
  { name: "Kak Ina & Pasangan", table: "11", jumlah: "2" },
  { name: "Kak Ita", table: "11", jumlah: "1" },
  { name: "Keluarga Alm. Pakde Ponco", table: "11", jumlah: "2" },
  { name: "Tante Atik", table: "12", jumlah: "3" },
  { name: "Tante Endang", table: "12", jumlah: "1" },
  { name: "Tante Wis", table: "12", jumlah: "1" },
  { name: "Tante Nana", table: "12", jumlah: "2" },
  { name: "Bude Tatik & Keluarga", table: "12", jumlah: "3" },
  { name: "Kak Elin & Keluarga", table: "13", jumlah: "5" },
  { name: "Om Tri & Keluarga", table: "13", jumlah: "3" },
  { name: "Mas Egy & Keluarga", table: "13", jumlah: "2" },
  { name: "Ko Albert & Ci Rosa", table: "14", jumlah: "3" },
  { name: "Ko Berry & Ci Meisya", table: "14", jumlah: "2" },
  { name: "Ko Jini & Ci Wenny", table: "14", jumlah: "2" },
  { name: "Ci Anna", table: "14", jumlah: "1" },
  { name: "Timothy & Phoebe", table: "14", jumlah: "2" },
  { name: "Pakde Cuk & Bude Enny (Wali Yoel)", table: "15", jumlah: "2" },
  { name: "Mas Erwin", table: "15", jumlah: "1" },
  { name: "Nadia", table: "15", jumlah: "1" },
  { name: "Pakde Ndoh & Mba Wika", table: "15", jumlah: "2" },
  { name: "Mbak Wuri & Keluarga", table: "15", jumlah: "4" },
  { name: "Tante Tutik & Keluarga", table: "16", jumlah: "3" },
  { name: "Om Joko & Keluarga", table: "16", jumlah: "2" },
  { name: "Tante Tanti & Keluarga", table: "16", jumlah: "4" },
  { name: "Mama & Wali Papa (Om Agus)", table: "17", jumlah: "2" },
  { name: "Jessica & Gisel (Adik Vania)", table: "17", jumlah: "2" },
  { name: "Om Edi & Keluarga", table: "17", jumlah: "2" },
  { name: "Mba Kiki & Keluarga", table: "17", jumlah: "3" },
  { name: "Pek Ik & Keluarga", table: "18", jumlah: "2" },
  { name: "Pek Han & Keluarga", table: "18", jumlah: "2" },
  { name: "CIk Intan & Keluarga", table: "18", jumlah: "4" },
  { name: "Ci Lian & Ko Jhon", table: "18", jumlah: "2" },
  { name: "Ko Ta & Keluarga", table: "19", jumlah: "3" },
  { name: "Ko David & Keluarga", table: "19", jumlah: "4" },
  { name: "Cicik", table: "20", jumlah: "1" },
  { name: "Ci Dizi & Keluarga", table: "20", jumlah: "3" },
  { name: "Fala Reva", table: "20", jumlah: "2" },
  { name: "Stephanie Wijaya", table: "20", jumlah: "1" },
  { name: "Ricky Natanael", table: "20", jumlah: "1" },
  { name: "Andy Wirawan (VIP)", table: "20", jumlah: "1" }
];
