const guests = [
  { name: "dr. Medika Bintang", table: "1", jumlah: "1" },
  { name: "dr. Armabar Oky", table: "1", jumlah: "1" },
  { name: "Alya Ermita", table: "1", jumlah: "1" },
  { name: "Dwi & Istri", table: "1", jumlah: "2" },
  { name: "Yurisda", table: "1", jumlah: "1" },
  { name: "Wahida Hera", table: "1", jumlah: "1" },
  { name: "Aisya Sekar", table: "1", jumlah: "1" },
  { name: "Dhea", table: "1", jumlah: "1" },
  { name: "Dhifa", table: "1", jumlah: "1" },
  { name: "Achmad Nu'man Annafis", table: "2", jumlah: "1" },
  { name: "Indah Puspitasari", table: "2", jumlah: "1" },
  { name: "Bani Rahmat Wijaya", table: "2", jumlah: "1" },
  { name: "Danny Gratia & Keluarga", table: "2", jumlah: "4" },
  { name: "Ester Novita Dwi", table: "2", jumlah: "2" },
];
